### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by idkjs** [diaozheng999/melange-stdlib#1]
Would it be possible to show an example of its usage?

Thank you for sharing.

**Comment by diaozheng999** [comment]
Hi!

This repo is to allow the use of `external-stdlib` key in `bsconfig.json`. If you're using [Melange](https://github.com/melange-re/melange), add the following to `package.json`

```json
{
  "dependencies": {
    "@rescript/std": "diaozheng999/melange-stdlib"
  }
}
```

And add the following to `bsconfig.json`

```json
{
  "external-stdlib": "@rescript/std"
}
```

This is helpful if you're using melange with non-standard environments (such as React Native) which do not follow symlink.

**Comment by idkjs** [comment]
Thank you. I will revert if any issues.
